import type { ReviewProps } from "./types/review";

export const reviews: ReviewProps[] = [
  {
    id: 1,
    author: "Timothy King",
    rating: 1,
    title: "Must natural policy society may.",
    body: "Better sea thus popular decision learn. Moment here modern how night natural career.",
    date: "2025-04-14T21:42:33.511083",
    likes: 9,
    product: "4K Monitor",
  },
  {
    id: 2,
    author: "Sherry Petersen",
    rating: 5,
    title: "Life thousand ok.",
    body: "Indicate movement decide per. Beautiful any nation bag character.",
    date: "2025-02-03T21:42:33.511303",
    likes: 83,
    product: "Charging Cable",
  },
  {
    id: 3,
    author: "David Castaneda",
    rating: 1,
    title: "Food know fine national.",
    body: "International bank dark skill him. Democrat car I write many agent. Decision image interesting president star become view list.",
    date: "2024-11-09T21:42:33.511459",
    likes: 39,
    product: "Wireless Headphones",
  },
  {
    id: 4,
    author: "Mark Norman",
    rating: 2,
    title: "Though determine goal do.",
    body: "But major radio middle three politics continue. Market issue fill generation cold writer. Himself you somebody budget base remember.",
    date: "2025-09-04T21:42:33.511605",
    likes: 11,
    product: "Bluetooth Speaker",
  },
  {
    id: 5,
    author: "Steven Smith",
    rating: 3,
    title: "Better region lose.",
    body: "War thank tend head and. Take according machine be share for.",
    date: "2024-12-15T21:42:33.511763",
    likes: 32,
    product: "Smartwatch",
  },
  {
    id: 6,
    author: "Lisa Walters",
    rating: 2,
    title: "Financial remain nearly.",
    body: "Management us especially learn field account big. Against reduce give bag hot voice. Pattern it final high. Forget hotel force question.",
    date: "2024-12-19T21:42:33.511907",
    likes: 32,
    product: "Mechanical Keyboard",
  },
  {
    id: 7,
    author: "Adrian Brewer",
    rating: 5,
    title: "Material election.",
    body: "Instead arm event open program nothing pull. Our statement father TV figure have.",
    date: "2025-01-13T21:42:33.512036",
    likes: 75,
    product: "4K Monitor",
  },
  {
    id: 8,
    author: "Gwendolyn Moore",
    rating: 4,
    title: "Sport write part listen.",
    body: "Development these guy. News those know idea.",
    date: "2024-12-29T21:42:33.512171",
    likes: 26,
    product: "4K Monitor",
  },
  {
    id: 9,
    author: "Alison Murphy",
    rating: 2,
    title: "Nation operation.",
    body: "Drug decision stage positive medical always. Program away prevent however local interest.",
    date: "2024-12-21T21:42:33.512300",
    likes: 2,
    product: "Bluetooth Speaker",
  },
  {
    id: 10,
    author: "Ricky Marquez",
    rating: 3,
    title: "Arrive figure course same.",
    body: "Care that road. Marriage class middle change free simple upon need. Thank build describe face magazine important.",
    date: "2024-12-09T21:42:33.512430",
    likes: 13,
    product: "Smartphone Case",
  },
  {
    id: 11,
    author: "Carla Molina",
    rating: 3,
    title: "Management theory stage.",
    body: "Daughter parent carry floor would. Authority throughout fire yourself admit. Note fine around law. Thus oil until technology.",
    date: "2025-03-02T21:42:33.512561",
    likes: 30,
    product: "Smartwatch",
  },
  {
    id: 12,
    author: "Eugene Stevens",
    rating: 5,
    title: "Same chance.",
    body: "Week the thank position yet begin bed. To development how miss green single every marriage. Most accept they low also media either.",
    date: "2025-08-16T21:42:33.512687",
    likes: 37,
    product: "4K Monitor",
  },
  {
    id: 13,
    author: "Angela Garcia",
    rating: 1,
    title: "Party set fill.",
    body: "Now interview investment news religious course. Stop ok ready project inside attorney defense.",
    date: "2025-02-13T21:42:33.512828",
    likes: 57,
    product: "Wireless Headphones",
  },
  {
    id: 14,
    author: "Pamela Coffey",
    rating: 4,
    title: "Value country including.",
    body: "Seem light leave rich. Daughter why interesting money than help.",
    date: "2025-08-28T21:42:33.513026",
    likes: 52,
    product: "Bluetooth Speaker",
  },
  {
    id: 15,
    author: "Dana Cole",
    rating: 2,
    title: "Good yet.",
    body: "Including same song exist somebody tough. Very official majority more.",
    date: "2024-11-28T21:42:33.513157",
    likes: 0,
    product: "Gaming Mouse",
  },
  {
    id: 16,
    author: "Julie Jones",
    rating: 1,
    title: "Wonder its national.",
    body: "Travel bad business couple plant. Wall director education need pass. Drop increase name seat people long him. Under cut success establish street yeah deal.",
    date: "2024-09-13T21:42:33.513299",
    likes: 33,
    product: "Charging Cable",
  },
  {
    id: 17,
    author: "Cynthia Howard",
    rating: 1,
    title: "Same just.",
    body: "Minute reduce chair head before study piece. Article career and heavy book our.",
    date: "2025-02-01T21:42:33.513422",
    likes: 91,
    product: "4K Monitor",
  },
  {
    id: 18,
    author: "Gerald Martin",
    rating: 4,
    title: "Commercial ever already police.",
    body: "Age win authority either. Risk star because positive account people.",
    date: "2024-09-25T21:42:33.513546",
    likes: 83,
    product: "Smartwatch",
  },
  {
    id: 19,
    author: "David Harvey",
    rating: 1,
    title: "Task can.",
    body: "Catch region cause real apply yet road. Education model professional second knowledge real analysis occur.",
    date: "2025-04-10T21:42:33.513675",
    likes: 57,
    product: "Gaming Mouse",
  },
  {
    id: 20,
    author: "Amber Willis",
    rating: 1,
    title: "Any bring reduce question.",
    body: "Finish of audience car. Charge rest little mouth present fine light. Though beat human knowledge respond gas try attention.",
    date: "2025-03-01T21:42:33.513835",
    likes: 30,
    product: "Smartphone Case",
  },
  {
    id: 21,
    author: "Sarah Kemp",
    rating: 4,
    title: "Keep but pretty.",
    body: "Down people leg main teacher win couple. Total put their history remember line.",
    date: "2025-08-26T21:42:33.513964",
    likes: 73,
    product: "Mechanical Keyboard",
  },
  {
    id: 22,
    author: "Daniel Allen",
    rating: 2,
    title: "Nearly instead develop.",
    body: "Even goal field increase design own. Class short determine meeting itself American. Discuss rock prove both data sister maintain.",
    date: "2025-08-19T21:42:33.514091",
    likes: 39,
    product: "Mechanical Keyboard",
  },
  {
    id: 23,
    author: "Emily Hernandez",
    rating: 1,
    title: "Born act prove Democrat management.",
    body: "Movement everyone stuff popular energy help. Still group mind off message leave.",
    date: "2025-09-05T21:42:33.514214",
    likes: 55,
    product: "Portable SSD",
  },
  {
    id: 24,
    author: "Keith Burch",
    rating: 2,
    title: "Other cover else.",
    body: "Lead because little foreign. Catch ready investment. Tend situation ball inside. Walk attention democratic read happy partner foreign.",
    date: "2024-11-28T21:42:33.514350",
    likes: 35,
    product: "Gaming Mouse",
  },
  {
    id: 25,
    author: "Sandra Brown",
    rating: 1,
    title: "Book role fact wonder.",
    body: "Well country firm there word. Size talk policy product minute. Force ask get election conference within. One huge base up space.",
    date: "2025-01-09T21:42:33.514481",
    likes: 66,
    product: "Bluetooth Speaker",
  },
  {
    id: 26,
    author: "Denise Anderson",
    rating: 3,
    title: "According event six debate enter.",
    body: "Appear show institution true discussion explain.",
    date: "2025-03-21T21:42:33.514602",
    likes: 87,
    product: "Smartphone Case",
  },
  {
    id: 27,
    author: "Mrs. Taylor Ochoa",
    rating: 3,
    title: "And public it.",
    body: "Own be avoid try argue participant force cell. Modern measure not point ever. Good exactly cultural.",
    date: "2025-01-24T21:42:33.514734",
    likes: 98,
    product: "Charging Cable",
  },
  {
    id: 28,
    author: "Holly Nicholson",
    rating: 1,
    title: "Adult bill argue on.",
    body: "See live of what my. Fly movie might nothing success trouble west. Increase rest happen usually.",
    date: "2024-11-13T21:42:33.514861",
    likes: 74,
    product: "Laptop Stand",
  },
  {
    id: 29,
    author: "Chad Brown",
    rating: 5,
    title: "Fund everybody husband star.",
    body: "Produce account region door go six. Stop group region most vote.",
    date: "2025-04-27T21:42:33.515000",
    likes: 22,
    product: "Wireless Headphones",
  },
  {
    id: 30,
    author: "Paul Kramer",
    rating: 4,
    title: "Assume road happen challenge.",
    body: "Because with ability appear. Pressure operation raise money letter.",
    date: "2025-01-03T21:42:33.515122",
    likes: 82,
    product: "Gaming Mouse",
  },
  {
    id: 31,
    author: "Candice Patterson",
    rating: 3,
    title: "Any road still main parent.",
    body: "See picture year speak state few. Staff walk type evening check.",
    date: "2025-05-25T21:42:33.515249",
    likes: 12,
    product: "4K Monitor",
  },
  {
    id: 32,
    author: "James Martinez",
    rating: 3,
    title: "Country provide respond who.",
    body: "Reason court whether reason movie director direction will. Look task past central.",
    date: "2025-01-02T21:42:33.515376",
    likes: 72,
    product: "Laptop Stand",
  },
  {
    id: 33,
    author: "Tyler Hansen",
    rating: 2,
    title: "Might down.",
    body: "Difficult catch degree.",
    date: "2025-01-05T21:42:33.515491",
    likes: 10,
    product: "Portable SSD",
  },
  {
    id: 34,
    author: "Andrea Martinez",
    rating: 4,
    title: "Bring do clear.",
    body: "Sign relationship agreement however out cover purpose. Light series region senior success seven wonder choice.",
    date: "2025-06-03T21:42:33.515613",
    likes: 88,
    product: "Wireless Headphones",
  },
  {
    id: 35,
    author: "Patricia Keller",
    rating: 4,
    title: "Sign hospital safe short.",
    body: "Hand finally course character. Food amount result end school what. Commercial forward stock benefit.",
    date: "2025-08-10T21:42:33.515739",
    likes: 34,
    product: "Charging Cable",
  },
  {
    id: 36,
    author: "Benjamin Anderson",
    rating: 2,
    title: "Him know wonder whatever speech.",
    body: "Land southern include. Election address foot fish system.",
    date: "2025-03-20T21:42:33.515859",
    likes: 93,
    product: "Smartphone Case",
  },
  {
    id: 37,
    author: "Angela Johnson",
    rating: 4,
    title: "Front last concern.",
    body: "And finally measure current. Thought box party woman commercial in unit. Save low toward toward ever either.",
    date: "2025-08-09T21:42:33.515998",
    likes: 36,
    product: "Laptop Stand",
  },
  {
    id: 38,
    author: "Anthony Ryan",
    rating: 2,
    title: "Sure scene fly.",
    body: "Ever hold me Republican ago eight trade. Hundred so position trial relate. Worker direction when inside fact deep teacher. A interesting fact science.",
    date: "2025-01-22T21:42:33.516126",
    likes: 79,
    product: "Smartphone Case",
  },
  {
    id: 39,
    author: "Mark Burke",
    rating: 4,
    title: "Through strategy.",
    body: "Mother goal pick customer debate. Compare task Congress professional memory force.",
    date: "2025-02-20T21:42:33.516246",
    likes: 79,
    product: "Bluetooth Speaker",
  },
  {
    id: 40,
    author: "Joseph Brown",
    rating: 3,
    title: "Affect debate send single us.",
    body: "Stuff save traditional also. Provide task possible building two daughter. Kid serve chance compare.",
    date: "2025-07-01T21:42:33.516368",
    likes: 43,
    product: "Laptop Stand",
  },
  {
    id: 41,
    author: "Edwin Whitaker",
    rating: 4,
    title: "Three health speech decade.",
    body: "Analysis film evidence late.",
    date: "2025-06-15T21:42:33.516484",
    likes: 59,
    product: "Wireless Headphones",
  },
  {
    id: 42,
    author: "Tina Gonzalez",
    rating: 3,
    title: "Own over mission fly.",
    body: "Make add explain budget. Respond event himself place real.",
    date: "2025-06-27T21:42:33.516608",
    likes: 16,
    product: "Charging Cable",
  },
  {
    id: 43,
    author: "Carrie Morris",
    rating: 2,
    title: "Daughter dream yes and.",
    body: "Push easy kind image successful school. Provide such control fight art.",
    date: "2025-07-20T21:42:33.516732",
    likes: 73,
    product: "4K Monitor",
  },
  {
    id: 44,
    author: "Kathy Cooper",
    rating: 2,
    title: "Boy billion truth rock.",
    body: "Listen song spend available speak I assume. State really grow per find cut store miss. Statement might happy sound. Probably consumer run life a offer.",
    date: "2024-09-25T21:42:33.516862",
    likes: 40,
    product: "4K Monitor",
  },
  {
    id: 45,
    author: "Dana Williams",
    rating: 5,
    title: "Open billion growth talk accept.",
    body: "We we sure often born food too project. Election really prevent each rather country. Even responsibility its fund.",
    date: "2025-01-02T21:42:33.517000",
    likes: 88,
    product: "Wireless Headphones",
  },
  {
    id: 46,
    author: "Jennifer Martin",
    rating: 5,
    title: "Newspaper significant decide notice herself.",
    body: "Over agreement right building cup class. Former picture son teacher example beat.",
    date: "2025-02-12T21:42:33.517134",
    likes: 22,
    product: "Mechanical Keyboard",
  },
  {
    id: 47,
    author: "Jeffery Benson",
    rating: 4,
    title: "Want first drive memory become.",
    body: "Into across personal. Likely still two traditional fight. Example share paper walk almost child almost.",
    date: "2024-09-18T21:42:33.517262",
    likes: 29,
    product: "Gaming Mouse",
  },
  {
    id: 48,
    author: "Jodi Flores",
    rating: 5,
    title: "Simply though could.",
    body: "Yet suffer career window mind. Others ability ok reach job.",
    date: "2025-07-24T21:42:33.517405",
    likes: 7,
    product: "Charging Cable",
  },
  {
    id: 49,
    author: "Brent Pena",
    rating: 1,
    title: "Right contain that trip.",
    body: "Decide goal choice thousand interview democratic boy industry. Catch fight stock contain charge. Attorney film man well we. Region author call hotel image individual.",
    date: "2025-07-21T21:42:33.517533",
    likes: 26,
    product: "Mechanical Keyboard",
  },
  {
    id: 50,
    author: "Anthony Hernandez",
    rating: 1,
    title: "Official consumer.",
    body: "Line least maintain air brother. However major little contain everything someone.",
    date: "2024-09-12T21:42:33.517654",
    likes: 27,
    product: "Smartwatch",
  },
];
